services:
  # --- ELYSIA APP (DEV) ---
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev # Geliştirme için olan Dockerfile'ı kullanır
    container_name: arena-backend-dev
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000" # .env'de yoksa varsayılan 3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_WARNING_TOPIC_ID=${TELEGRAM_WARNING_TOPIC_ID}
      - TELEGRAM_INFO_TOPIC_ID=${TELEGRAM_INFO_TOPIC_ID}
      - TELEGRAM_ERROR_TOPIC_ID=${TELEGRAM_ERROR_TOPIC_ID}
      - TELEGRAM_CRITICAL_TOPIC_ID=${TELEGRAM_CRITICAL_TOPIC_ID}
    volumes:
      - .:/app # Kodunu içeri yansıtır (Hot Reload için şart)
      - /app/node_modules # Konteynerin kendi modüllerini korur (ÖNEMLİ)
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - arena-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: job=arena-backend-dev,env=development
    # Loglar doğrudan lokiye gider, console'a yazmaz.
    command: [ "bun", "run", "--watch", "src/index.ts" ]

  # --- POSTGRES (DEV) ---
  postgres:
    image: postgres:15-alpine
    container_name: arena-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Geliştirme yaparken DB araçlarıyla bağlanabilmen için port açık
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - arena-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: job=arena-postgres-dev,env=development
    # Loglar doğrudan lokiye gider, console'a yazmaz.

    # --- REDIS (DEV) ---
  redis:
    image: redis:alpine
    container_name: arena-redis-dev
    restart: always
    ports:
      - "6379:6379" # Geliştirme yaparken Redis GUI ile bakabilmen için açık
    volumes:
      - redis_data_dev:/data
    networks:
      - arena-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: job=arena-redis-dev,env=development
    # Loglar doğrudan lokiye gider, console'a yazmaz.

  pgweb:
    image: ghcr.io/sosedoff/pgweb:latest
    container_name: arena-pgweb-dev
    ports:
      - 8081:8081
    networks:
      - arena-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGWEB_DATABASE_URL: postgresql://admin:cok_gizli_sifre@postgres:5432/arena_db?sslmode=
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: job=arena-pgweb-dev,env=development
    # Loglar doğrudan lokiye gider, console'a yazmaz.

    # --- MONITOR (DEV) ---

  prometheus:
    image: prom/prometheus:latest
    container_name: arena-prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - arena-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:latest
    container_name: arena-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml
    networks:
      - arena-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: arena-promtail
    restart: unless-stopped
    volumes:
      - ./config/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - arena-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: arena-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - arena-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  arena-network:
    driver: bridge

volumes:
  postgres_data_dev:
  redis_data_dev:
