{
 "title": "Arena API Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"arena-api\"}[1m])",
     "legendFormat": "CPU Core Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{app=\"arena-api\"}) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{route}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "description": "Less is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{app=\"arena-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{route}} (95th percentile)"
    }
   ]
  },
  {
   "title": "404 Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status_code=\"404\"}[1m])",
     "legendFormat": "404 Errors"
    }
   ]
  },
  {
   "title": "Garbage Collection Duraiton",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{app=\"arena-api\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "active_requests{app=\"arena-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container=\"arena-backend-dev\"}"
    }
   ]
  }
 ]
}