apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      # Prometheus ile korelasyon (log satırından metriğe atlama)
      derivedFields:
        - name: "TraceID"
          matcherRegex: "trace_id=(\\w+)"
          url: ""
          datasourceUid: ""
      # Grafana Explore Logs (Drilldown) için servis haritası
      serviceMap:
        datasourceUid: "Prometheus"
      # Maksimum log satırı
      maxLines: 1000
      # Explore Logs'ta kullanılacak label
      lokiDerivedFields: []
